name: Documentation Build

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  docs_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Build HTML Documentation
        run: |
          pip install -r requirements_docs.txt --disable-pip-version-check
          make -C doc html SPHINXOPTS="-W"
          touch doc/build/html/.nojekyll
          echo "dev.docs.pyansys.com" > doc/build/html/CNAME
  
      - name: Build PDF Documentation
        run: |
          sudo apt update
          sudo apt-get install -y texlive-latex-extra latexmk
          make -C doc latexpdf

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v2.2.4
        with:
          name: HTML-Documentation
          path: doc/build/html
          retention-days: 7

      - name: Upload PDF Documentation
        uses: actions/upload-artifact@v2.2.4
        with:
          name: PDF-Documentation
          path: doc/build/latex/*.pdf
          retention-days: 7

  Release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: docs_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/download-artifact@v4.1.7

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages
          folder: HTML-Documentation
          clean: true
          single-commit: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./*PDF*/*.pdf
